services:
  assets:
    image: ghcr.io/techtonic-plates-blog/assets-service:nightly
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS=${MINIO_ACCESS}
      - MINIO_SECRET=${MINIO_SECRET}
    networks:
      - techtonic_plates_network
    ports:
      - "5134:5000"

networks:
  techtonic_plates_network:
    external: true