services:
  assets:
    image: ghcr.io/techtonic-plates-blog/assets-service:nightly
    pull_policy: always

    env_file:
      - .assets.env
    networks:
      - techtonic_plates_network
    ports:
      - "5134:5000"

networks:
  techtonic_plates_network:
    external: true