services:
  images:
    image: ghcr.io/techtonic-plates-blog/images-service:nightly
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS=${MINIO_ACCESS}
      - MINIO_SECRET=${MINIO_SECRET}
    networks:
      - techtonic_plates_network
    ports:
      - "5133:5000"

networks:
  techtonic_plates_network:
    external: true