services:
  auth:
    image: ghcr.io/techtonic-plates-blog/auth-service:nightly
    env_file:
      - .auth.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://techtonic:Jkjz1yG9bKcWBeB1zFdgqg@postgres:5432/posts_service}
    networks:
      - techtonic_plates_network
    ports:
      - "5133:5000"

networks:
  techtonic_plates_network:
    external: true